version: 5.6.2.{build}
environment:
  matrix:
  - SCRIPT: visual-studio
    VS_VERSION: 14
  - SCRIPT: visual-studio
    VS_VERSION: 12
  - SCRIPT: visual-studio
    VS_VERSION: 11
  - SCRIPT: visual-studio
    VS_VERSION: 10
  - SCRIPT: mingw32
configuration: Debug
build_script:
- scripts\appveyor\%SCRIPT%.bat
